- data.json
What ?
Add file data.json to the root
Why ?
To get an idea of what needs to be extracted for the API for the job board.
> #2-Create a json file-SanaAsaf

- client/src/index.html
> #3-Semantic-HTML-Meysam-Arshadi

- client/src/Footer.jsx
Fixes #14 
Footer.jsx was created at src folder.
Basic code added to the file.
Checklist:
My code follows the style guidelines of this project
I have carefully reviewed my own code
I have commented my code
I have updated any documentation
> #14-Footer.jsx-created-Meysam-Arshadi

- client/src/Header.jsx
> #13-Header.jsx-created-Meysam-Arshadi

- server/api.js
- create route to get jobs
- so client can request jobs, to confirm working connection, to display jobs
Fixes #5 
- you need a json file in the root folder with data or 
- create a json file at the location that has been commented out and uncomment the import statement.
> #5-added-route-for-json-data-Olus

- client/src/pages/Home.css
- client/src/pages/Home.js
- server/api.js
- added route to app.js
- added css margin for anchor tag
- updated h1 message in home to JOBS BOARD
Fixes #30
> #30-hotfix-link-jobs-to-home-Olus

- client/src/App.js
- client/src/components/Footer.jsx
- client/src/components/Header.jsx
- client/webpack/dev.config.js
- package-lock.json
- package.json
> #29-Header-Footer-added-to-App.js-Meysam-Arshadi

- client/src/App.js
- client/src/components/Search.jsx
36-Search-Sana
Created a Search component and add it to App.js
Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:
Fixes #36 
https://github.com/OlushoreOdude/nyf-job-board/pull/39
> Search component created and added to app.js

- client/src/App.js
- client/src/components/Footer.css
- client/src/components/Footer.jsx
- client/src/components/Header.css
- client/src/components/Header.jsx
- client/src/global.css
- client/src/pages/Home.css
- client/src/pages/Home.js
- client/src/pages/Jobs.js
Fixes [#35](https://github.com/OlushoreOdude/nyf-job-board/issues/35)
Footer.css and Header.css created.
Basic style to both files done.
> #35-created-Header.css-Footer.css+basic-styling

- client/webpack/common.config.js
dev branch for testing solution for issue #45
> 45 updated webpace for jsx as causin deployment to fail - olus

- client/webpack/common.config.js
updated webpack for jsx as causing deployment to fail
Fixes #45 
updated webpack for jsx as causing deployment to fail
> 45-updated webpace for jsx as causin deployment to fail-olus

- package-lock.json
- package.json
- server/api.js
> #9-Fetch-data-from-the-API 

- client/src/pages/Home.js
Modified home.js and display data from Rapid.api [JSearch jobs library](https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch).
npm install axios and npm install @babel/core @babel/cli @babel/preset-env --save-dev to be able to use the Rapid.api JSearch jobs library
Fixes #58
> 58-Update Home.js-Sana

- client/src/App.js
- client/src/components/Search.jsx
- client/src/pages/Home.js
> #41_Search_components_AliDashti

- client/src/components/JobCardContainer.jsx
- client/src/pages/Home.js
Added JobCardContainer.jsx as a Component
Displayed the Component on Home.js
Fixes #38
> #38-Add_Job_CardContainer-Sana

- client/src/App.js
- client/src/components/Header.css
- client/src/components/Header.jsx
- client/src/pages/SearchDb.js
- add Navlink in home page that links to page that fetches data from the database
- add active class to nav link so user knows which page there on
Fixes #70 
deliverable 
[x] user know which page there on
[x] can link to search Db from home 
[x] nav links styled and responsive
> #70 added nav and searchDb page with for db search-olus

- client/src/components/Card.css
- client/src/components/CardButtonShowJob.jsx
- client/src/components/SearchOnDb.jsx
- client/src/pages/SearchDb.css
- client/src/pages/SearchDb.js
- server/api.js
created components to interact with searchdb page
Fixes #72
> #72-page and components added-olus

- client/src/App.js
- client/src/utils/externalApiFunc.js
- server/api.js
create functions for external Api call 
Fixes #74
> #74 function to manage external api's- olus

- client/src/components/Footer.css
- client/src/components/Header.css
- client/src/components/JobCardContainer.jsx
- client/src/pages/Home.css
- client/src/pages/Home.js
> #61-Applied-general-styling-to-Home.js-Header.js-Footer.js

- client/src/components/CardButtonShowJob.jsx
On Local deployment the app was failing .The fix was to rename card.css as Card.css with a Capital C
Fixes #86
> #86-Rename Card.css-Sana

- client/src/components/JobCard.jsx
- client/src/components/JobCardContainer.jsx
- client/src/pages/Home.js
> #78-Create-JobCard-Component-Meysam-Arshadi

- client/src/components/JobCard.jsx
- client/src/components/JobCardContainer.jsx
- client/src/components/SelectedJob.jsx
- client/src/pages/Home.js
> #79-Create-SelectedJob-component&display-selected-job-detail

- client/src/components/JobCardContainer.css
- client/src/components/JobCardContainer.jsx
- client/src/pages/Home.css
> #95-JobCardContainer.css-created-basic-styling-added

- server/utils/fetchRapidData/createApiKey.js
- server/utils/fetchRapidData/createOptions.js
- server/utils/fetchRapidData/index.js
- server/utils/fetchRapidData/makeFetch.js
- server/utils/transformData/index.js
- server/utils/transformData/nomaliseOneJobObj/index.js
- server/utils/transformData/nomaliseOneJobObj/nomalizeOneJobObject.js
- server/utils/transformData/nomaliseOneJobObj/normalizeOneObject.js
- server/utils/transformData/nomaliseOneJobObj/processProperty.js
transforms data to fit a predefined model, model will be updated to reflect new db schema
#10
> 10-backend-server-transform-fn-Olus

- server/utils/fetchRapidData/createApiKey.js
- server/utils/fetchRapidData/createOptions.js
- server/utils/fetchRapidData/index.js
- server/utils/fetchRapidData/makeFetch.js
function currently fetches Rapid only but will add Arbit in the next upgrade
#77 
- [x ] I have carefully reviewed my own code
- [x ] I have commented my code
> 77-fetchRapid function mvp

- server/utils/fetchRapidData/createApiKey.js
- server/utils/fetchRapidData/createOptions.js
- server/utils/fetchRapidData/index.js
- server/utils/fetchRapidData/makeFetch.js
- server/utils/insertData/checkAndReplaceWithNull.js
- server/utils/insertData/dbConnect.js
- server/utils/insertData/extractAllData.js
- server/utils/insertData/index.js
- server/utils/insertData/insertJobsData.js
- server/utils/priorityObjectSchema/index.js
- server/utils/priorityObjectSchema/priorityObj.json
- server/utils/priorityObjectSchema/priotiyObj.js
- server/utils/transformData/index.js
- server/utils/transformData/nomaliseOneJobObj/index.js
- server/utils/transformData/nomaliseOneJobObj/nomalizeOneJobObject.js
- server/utils/transformData/nomaliseOneJobObj/normalizeOneObject.js
- server/utils/transformData/nomaliseOneJobObj/processProperty.js
insert data function and priority object. both need to be updated to fit the current schema, will do after testing current versions works on deployed site.
#11
> 11-backend-server-insert-data-priority-Olus

- .gitignore
- server/api.js
- server/utils/fetchRapidData/createApiKey.js
- server/utils/fetchRapidData/createOptions.js
- server/utils/fetchRapidData/index.js
- server/utils/fetchRapidData/makeFetch.js
- server/utils/insertData/checkAndReplaceWithNull.js
- server/utils/insertData/dbConnect.js
- server/utils/insertData/extractAllData.js
- server/utils/insertData/index.js
- server/utils/insertData/insertJobsData.js
- server/utils/priorityObjectSchema/index.js
- server/utils/priorityObjectSchema/priorityObj.json
- server/utils/priorityObjectSchema/priotiyObj.js
- server/utils/refreshData/ReadMe.md
- server/utils/refreshData/index.js
- server/utils/refreshData/refreshFunc.js
- server/utils/transformData/index.js
- server/utils/transformData/nomaliseOneJobObj/index.js
- server/utils/transformData/nomaliseOneJobObj/nomalizeOneJobObject.js
- server/utils/transformData/nomaliseOneJobObj/normalizeOneObject.js
- server/utils/transformData/nomaliseOneJobObj/processProperty.js
refresh function and rout that invoke the fetch, transform and inset function
Fixes #85  and #84
> 85-backend-server-refresh-data-olus

- client/src/components/JobCard.css
- client/src/components/JobCard.jsx
- client/src/components/SelectedJob.css
- client/src/components/SelectedJob.jsx
- client/src/pages/Home.css
> #94-SelectedJob.css-created-styled-Meysam-Arshadi

- client/src/components/Footer.css
- client/src/components/Header.css
- client/src/components/JobCard.css
- client/src/components/JobCardContainer.css
- client/src/components/SelectedJob.css
- client/src/pages/Home.css
Fixes #103 
**NOTE:** 
I suggest we adjust the display of components such that the homepage showcases only the search options and job cards for smaller screens. Selected job details should open in a new page to maintain a clean and intuitive user interface.
> #103-Responsive-design-implemented-to-existing-CSS-files

- server/utils/fetchArbeitnowData/index.js
In Utils Folder Created a folder to put in the FetchArbeitnowData.js
The fetchArbeitnowData.js uses the axios library to make a GET request to the "https://www.arbeitnow.com/api/job-board-api" endpoint. It retrieves data from the external API and returns the response data. If any error occurs during the request, the function logs the error and throws an exception with a descriptive error message.
Fixes #77
> #77_fetchArbeitnowData_Sana

- client/src/components/SearchForm.jsx
- client/src/pages/Home.js
Fixes #116 
Note: More filters will be added to S`earchByTitle.jsx.`
> 116-search-from-component-filter-by-location-was-added-Ali-Dashti

- client/src/components/SearchForm.jsx
> #122-add-filter-by-type-to-Search.jsx-AliDashti

- client/src/components/SearchForm.css
- client/src/components/SearchForm.jsx
> #123-SearchForm.css-created-styling-added-AliDashti

- client/src/components/SearchForm.css
- client/src/components/SearchForm.jsx
> #133-additionalstyling-added-to-SerachForm.jsx-for-job-types-AliDashti

- client/src/pages/Home.css
- client/src/pages/Home.js
Fixes #106 
Implemented a smooth scrolling animation to enhance user experience when interacting with job cards on the homepage, especially for smaller responsive screens.
Now, when a user clicks on a job card, the page will smoothly scroll down or up to reveal the selected job details located at the bottom of the column.
Changes Made:
- Integrated smooth scrolling behavior using the 'scroll-behavior' `Home.CSS` and `Home.js` property.
- Added 'scroll-margin-top' to sections for precise scrolling alignment.
> #106-added-smooth-scrolling-animation-Meysam-Arshadi

- client/src/components/JobCard.jsx
- client/src/components/SelectedJob.jsx
- client/src/pages/Home.js
- server/api.js
> #149-Fetch-data-from-transformRes-Arbeitnow.json-and-display-filtered-result-Ali-Dashti

- client/src/pages/Home.js
- server/api.js
Description: used internal transformRes_Arbeitnow.json in api.js and created new routes for searching and displaying first 10 jobs in the page.
and fetch the data from new routes in Home.js.
Fixes #151
> #151-api-routers-are-working-and-data-displayes-on-the-pages

- client/src/pages/Home.js
- server/utils/routeHandlers/selectAllFromDb.js
> #158-data-base-route-added-to-the-main.js-to-display-jobs-on-landing page-Ali-Dashti

- client/src/pages/Home.js
> #158-jobs-filtered-in-front-end

- client/src/pages/Home.js
Updated Home.js
As well as api.js
> Search working for title , Location and is-remote

- client/src/pages/Home.js
Home.js updated to display the filtered job
> Filter bug fixed in home.js

- client/src/components/Header.jsx
- client/src/components/JobCardContainer.jsx
- client/src/pages/Home.js
the first job at the landing page is highlighted, when a user select a job, the selected job is highlighted, and the first job is deselected. 
searchDb button text changed to Login
> highlighted job sorted and searchDb button text changed to Login
